import Head from 'next/head'
import Link from 'next/link'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Login() {
  return (
    <div className="mobile">
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main className="main auth-bg">
        <div className="container">

          {/* IMAGE AVATAR */}
          <div className="row">
            <div className="col"/>
            <div className="col-6">
              <div>
                <i className="bi bi-person defAva"></i>
              </div>
            </div>
            <div className="col" />
          </div>

          {/* FORM LOGIN */}
          <div className="row">
            <div className="col" />
            <div className="col-10">
            
              <div className="text-center main-text-cl">Selamat Datang !</div>
              <div className="text-center">Silahkan masuk ke akun anda.</div>
              
              <form action="/" method="post">
                <input type="email" className="formtype form-control mb-3" id="email" placeholder="contoh@mail.com" />
                <input type="password" className="form-control mb-3" id="password" placeholder="kata kunci" />
                
                <div className="text-end">
                  <Link href="login/forgot-password">
                    <a className="aStyle"> Lupa Kata Kunci ?</a>
                  </Link>
                </div>

                <div className="d-grid gap-2">
                  <button type="submit" className="button">Masuk</button>
                </div>
              </form>

              <div className="text-center">Belum punya akun? 
                <Link href="register">
                  <a className="main-text-cl aStyle"> Daftar</a>
                </Link>
              </div>

            </div>
            <div className="col" />
          </div>

        </div>
      </main>
    </div>
  )
}
