import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function RegisterCode() {
  return (
    <div className="mobile" >
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main className="main auth">
        <h1>6 number code</h1>






        {/* <a href="#">
          <i className='bi bi-linkedin'></i> linkedin
        </a> */}
      </main>

    </div>
  )
}
