import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function ProfileLikedRecipe() {
  return (
    <div
      // className={styles.mobile}
    >
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main>
        <h1>User liked recipes</h1>






        {/* <a href="#">
          <i className='bi bi-linkedin'></i> linkedin
        </a> */}
      </main>

    </div>
  )
}
