import Head from 'next/head'
// import Link from 'next/link'
// import Image from 'next/image'

export default function ChatId() {
  return (
    <div className="mobile" >
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="main bg-light">
        <h1>chat to user by its id</h1>





      </main>
    </div>
  )
}
