import Head from 'next/head'
// import Link from 'next/link'
// import Image from 'next/image'
import NavHome from '../components/organism/navHome'

export default function Chat() {
  return (
    <div className="mobile" >
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>chat to user by id user</h1>
      </main>
      <NavHome />

    </div>
  )
}
