import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";

// params id not number? invalid url
export default function DetailRecipe() {
  const { query } = useRouter();
  
  return (
    <div className="mobile" >
      <Head>
        <title>Detail Resep</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      
      {/* <main > */}
      {/* </main> */}

        <div id='imagesection'>
          <img 
            src='http://localhost:8000/images/food_images/foodImage_11.jpeg'
            // width='100%'
            id="imagedetailrecipe"
            className='b-5'
          />
        </div>

        <div id='descsection' className='bg-primary pt-5'>
          <div className='container'>

            <h4>Bahan-bahan</h4>
            <h5 className='mb-5'>lorem ipsum</h5>

            <h4>Vidio</h4>
            <h5 className='mb-5'>lorem ipsum</h5>

            {/* KOMENTAR KE RESEP */}
            <form action="/" method="post" className='mb-5'>
              <textarea type="text" className="form-control mb-3" id="name" placeholder="Masukkan komentar ..." rows="7"/>
              <div className="d-grid gap-2">
                <button type="submit" className="button">Kirim Komentar</button>
              </div>
            </form>

            {/* TAMPILAN KOMENTAR_KOMENTAR YANG SUDAH DIBERIKAN */}
            <h4>Semua komentar</h4>
            <div className='row pt-3'>
              <div className='col-2'>
                <img 
                  src='http://localhost:8000/images/food_images/foodImage_11.jpeg'
                  style={{borderRadius: "50%", width:'3rem', height:'3rem'}}
                />
              </div>
              <div className='col-10'>
                <h5 className='bold'>Nama pengkomentar 1</h5>
                <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime</h5>
              </div>
            </div>
            <div className='row pt-3'>
              <div className='col-2'>
                <img 
                  src='http://localhost:8000/images/food_images/foodImage_3.jpeg'
                  style={{borderRadius: "50%", width:'3rem', height:'3rem'}}
                />
              </div>
              <div className='col-10'>
                <h5 className='bold'>Nama pengkomentar 2</h5>
                <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime</h5>
              </div>
            </div>
            <div className='row pt-3'>
              <div className='col-2'>
                <img 
                  src='http://localhost:8000/images/food_images/foodImage_4.jpeg'
                  style={{borderRadius: "50%", width:'3rem', height:'3rem'}}
                />
              </div>
              <div className='col-10'>
                <h5 className='bold'>Nama pengkomentar 3</h5>
                <h5>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime</h5>
              </div>
            </div>
          </div>
        </div>
        
        



        {/* <h1>detail recipe by id recipe= {query.id} </h1>
        <img 
          src='http://localhost:8000/images/food_images/foodImage_11.jpeg'
          wi
        /> */}
        
    </div>
  )
}
