import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";

// params id not number? invalid url
export default function DetailRecipe() {
  const { query } = useRouter();
  
  return (
    <div className="mobile" >
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      
      <main className="main bg-light">
        <h1>detail recipe by id recipe= {query.id} </h1>
        
      </main>
    </div>
  )
}
