import Head from 'next/head'
// import Image from 'next/image'
import {useRouter} from "next/router";
import {useState} from "react";
import Link from 'next/link'

export async function getServerSideProps(context){
  const api = 'http://localhost:8000/recipes/show/name?name='
  const params = context.query.name;

  const datasearch = await fetch( `${api}${params}` )
    .then((response) => response.json())
    .catch(() => null);

  return {
    props: {
      datasearch,
    }
  }
};

export default function SearchRecipe(props) {
  const datas = props?.datasearch?.data;
  const urlIdRecipe = 'http://localhost:3000/detail/'

  const [Searching, setSearching] = useState([]);
  const handleSearchingName = () => {
    window.location.href=`http://localhost:3000/search/${Searching}`
  };
  
  const { query } = useRouter();
  return (
    <div className="mobile">
      <Head>
        <title>Search Recipes</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main>
        <div className="container">

          <section className="mt-5 ">
            <form>
              <div className="row">
                <div className="col-9">
                  <div 
                    className="input-group"
                    style={{
                      border: "none",
                      "boxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                      "WebkitBoxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                      "MozBoxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                    }}
                  >
                    <i className="input-group-text bi bi-search bg-white" id="logosearch"></i>
                    <input
                      placeholder="Search Pasta, Bread, etc"
                      type="search"
                      className="form-control"
                      id="searchinput"
                      onChange={(e) => setSearching(e.target.value)}
                    />
                  </div>
                </div>
                <div className="col-3">
                  <button id="searchbutton"
                    type='button'
                    onClick={handleSearchingName}
                  >Search</button>
                </div>
              </div>
            </form>
          </section>

          {datas
            ? datas?.map((data) => (
                <div
                  key={data.recipe_id}
                  className="card"
                  style={{
                    borderRadius: "15px",
                    padding: "10px",
                    border: "none",
                    "boxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                    "WebkitBoxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                    "MozBoxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                    marginBottom: "20px",
                    cursor: "pointer",
                  }}
                >
                <Link href={`${urlIdRecipe}${data.recipe_id}`}>
                  <div className="row">
                    <div className="col-2">
                      

                      {/* TIDAK BISA PAKAI NEXT/IMAGE */} {/* CARA GABUNGKAN 2 VARIABEL KEDALAM 1 SRC */}

                      <img
                        src="http://localhost:8000/images/food_images/foodImage_11.jpeg"
                        // src="/images/food_images/foodImage_11.jpeg"
                        // src={data.image_recipe}
                        width="80px"
                        height="80px"
                        style={{ borderRadius: "16px", objectFit: "cover", marginTop: "7px" }}
                        alt="image"
                      />
                    </div>
                    <div className="col-10">
                      <div style={{ marginLeft: "20px" }}>
                        <h6>{data.name_recipe}</h6>
                        <p className='p4'>Spicy, Salted, Tasty</p>
                        <div className="d-flex gap-1 align-items-center">
                          <span className='p4'>4.7</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
                </div>
              ))
            : <div className='text-center alert alert-warning py-1 px-5'>No one recipe has named "{query.name}"</div>
          } 



        </div>
      </main>

    </div>
  )
}