import Head from 'next/head'
// import Image from 'next/image'
import NavHome from './components/organism/navHome'

export default function AddRecipe() {
  return (
    <div className="mobile" >
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>add recipe page</h1>






      </main>
      <NavHome />
    </div>
  )
}
