import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function DetailRecipe() {
  return (
    <div className={styles.mobile}>
      <Head>
        <title>Bitri Recipe</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1>detail recipe by id recipe</h1>






        {/* <a href="#">
          <i className='bi bi-linkedin'></i> linkedin
        </a> */}
      </main>

    </div>
  )
}
