import Head from 'next/head'
// import Link from 'next/link'
import Home1 from '../components/organism/home/sect1'
import Home2 from '../components/organism/home/sect2'
import Home3 from '../components/organism/home/sect3'
import Home4 from '../components/organism/home/sect4'
import NavHome from '../components/organism/navHome'

export default function Home(props) {
  // console.log(props);
  
  return (
    <div className="mobile" >
      <Head>
        <title>Home</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main>
        <div className="container">

          {/* SEARCH RECIPES - HOME */}
          <section className="mt-5 "> <Home1 /> </section> 

          {/* CATEGORY RECIPE - HOME */}
          <section> <Home2 /> </section> 

          {/* NEWEST RECIPES - HOME */}
          <section> <Home3 data3={props.dataHome3.data} /> </section> 

          {/* ALL POPULAR RECIPES - HOME */}
          <section> <Home4 data4={props.dataHome4.data} /> </section> 
        </div>
      </main>
      <NavHome />
    </div>
  )
}

export async function getServerSideProps(context){
  const dataHome3 = await fetch( "http://localhost:8000/recipes/show/all" ).then((response) => response.json());
  const dataHome4 = await fetch( "http://localhost:8000/recipes/show/new" ).then((response) => response.json());
   
  return {
    props: {
      dataHome3,
      dataHome4,
    }
  }
};
