import Head from 'next/head'
// import Link from 'next/link'

import NavHome from './components/organism/navHome'
import Home1 from './components/organism/home/sect1'
import Home2 from './components/organism/home/sect2'
import Home3 from './components/organism/home/sect3'
import Home4 from './components/organism/home/sect4'

export default function Home() {
  return (
    <div className="mobile" >
      <Head>
        <title>Home</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main>
        <div className="container">

          {/* SEARCH RECIPES - HOME */}
          <section className="mt-5">
            <Home1 />
          </section>

          {/* POPULAR RECIPES FOR USER - HOME */}
          <section className="mb-4">
            <Home2 />
          </section>
          
          {/* NEWEST RECIPES - HOME */}
          <section className="mb-4">
            <Home3 />
          </section>

          {/* ALL POPULAR RECIPES - HOME */}
          <section className="mb-5" >
            <Home4 />
          </section>

        </div>
      </main>

      <NavHome />

    </div>
  )
}
