import Head from 'next/head'
// import Image from 'next/image'
import Home1 from '../components/organism/home/sect1'

export async function getServerSideProps(context){
  const search = await fetch( "http://localhost:8000/recipes/show/new" ).then((response) => response.json());
   console.log(search);
  return {
    props: {
      search,
    }
  }
};

export default function SearchRecipe(props) {
  // console.log(props);
  const datas = props.search.data;
  return (
    <div className="mobile">
      <Head>
        <title>Search Recipes</title>
        <meta charSet="utf-8"/>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>

      <main>
        <div className="container">
          <section className="mt-5 "> <Home1 /> </section> 
                    
          {datas?.map((data) => (
            <div
              key={data.id_recipe}
              className="card"
              style={{
                borderRadius: "15px",
                padding: "10px",
                border: "none",
                "boxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                "WebkitBoxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                "MozBoxShadow": "2px 2px 5px 1px rgba(0,0,0,0.12)",
                marginBottom: "20px",
                cursor: "pointer",
              }}
            >
            {/* <ul>
              {names.map((name) => (
                <li key={name}>{name}</li>
              ))}
            </ul> */}
              <div className="row">
                <div className="col-2">
                  


                  {/* TIDAK BISA PAKAI NEXT/IMAGE */} {/* CARA GABUNGKAN 2 VARIABEL KEDALAM 1 SRC */}

                  <img
                    src="http://localhost:8000/images/food_images/foodImage_11.jpeg"
                    // src="/images/food_images/foodImage_11.jpeg"
                    // src={data.image_recipe}
                    width="80px"
                    height="80px"
                    style={{ borderRadius: "16px", objectFit: "cover", marginTop: "7px" }}
                    alt="image"
                  />
                </div>
                <div className="col-10">
                  <div style={{ marginLeft: "20px" }}>
                    <h6>{data.name_recipe}</h6>
                    <p>Spicy, Salted, Tasty</p>
                    <div className="d-flex gap-1 align-items-center">
                      {/* <img
                        src="/images/star.png"
                        alt="star"
                        height="12px"
                      /> */}
                      <span>4.7</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </main>

    </div>
  )
}